# syntax=docker/dockerfile:1.2

FROM ghcr.io/pnx-si/geonature-frontend:develop

RUN echo -e '\
    server { \n\
    listen 80; \n\
    location / { \n\
    root /usr/share/nginx/html; \n\
    index index.html index.htm; \n\
    try_files $uri $uri/ /index.html; \n\
    } \n\
    error_page 500 502 503 504 /50x.html; \n\
    location = /50x.html { \n\
    root /usr/share/nginx/html; \n\
    } \n\
    } \n\
    ' > /etc/nginx/templates/default.conf.template
