services:
  traefik:
    image: traefik:3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      # Observability
      TRAEFIK_LOG_LEVEL: "INFO"
      TRAEFIK_ACCESSLOG: "${TRAEFIK_ACCESS_LOG:-true}"
      # Dashboard
      TRAEFIK_API_DASHBOARD: "true"
      # Providers
      TRAEFIK_PROVIDERS_DOCKER: "true"
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: "false"
      # EntryPoints
      TRAEFIK_ENTRYPOINTS_DASHBOARD_ADDRESS: ":${TRAEFIK_DASHBOARD_PORT:-8080}"
      TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: ":${TRAEFIK_HTTP_PORT:-80}"
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ./config/traefik/dynamic:/dynamic
    ports:
      - ${TRAEFIK_DASHBOARD_PORT:-8080}:${TRAEFIK_DASHBOARD_PORT:-8080}
      - ${TRAEFIK_HTTP_PORT:-80}:${TRAEFIK_HTTP_PORT:-80}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=dashboard"
      - "traefik.http.routers.dashboard.service=api@internal"

  geonature-backend:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geonature-backend.rule=Host(`${GEONATURE_BACKEND_HOST}`) && PathPrefix(`${GEONATURE_BACKEND_PREFIX}`)"
      - "traefik.http.routers.geonature-backend.entrypoints=web"
      - "traefik.http.services.geonature-backend.loadbalancer.server.port=8000"

  geonature-frontend:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geonature-frontend.rule=Host(`${GEONATURE_FRONTEND_HOST}`) && PathPrefix(`${GEONATURE_FRONTEND_PREFIX}`)"
      - "traefik.http.routers.geonature-frontend.entrypoints=web"
      - "traefik.http.services.geonature-frontend.loadbalancer.server.port=80"

  usershub:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usershub.rule=Host(`${USERSHUB_HOST}`) && PathPrefix(`${USERSHUB_PREFIX}`)"
      - "traefik.http.routers.usershub.entrypoints=web"
      - "traefik.http.services.usershub.loadbalancer.server.port=5001"
