x-validation:
  http: "${TRAEFIK_HTTP_PORT?leave empty to use port 80 but define me!}"

services:
  traefik:
    image: traefik:3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      # Observability
      TRAEFIK_LOG_LEVEL: "INFO"
      TRAEFIK_ACCESSLOG: "${TRAEFIK_ACCESS_LOG:-false}"
      # Providers
      TRAEFIK_PROVIDERS_DOCKER: "true"
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: "false"
      TRAEFIK_PROVIDERS_DOCKER_CONSTRAINTS: "Label(`com.docker.compose.project`, `${COMPOSE_PROJECT_NAME}`)"
      # EntryPoints
      TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: ":${TRAEFIK_HTTP_PORT:-80}"
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ./config/traefik/dynamic:/dynamic
    ports:
      - ${TRAEFIK_HTTP_PORT:-80}:${TRAEFIK_HTTP_PORT:-80}
    labels:
      - "traefik.enable=true"

  geonature-backend:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geonature-backend.rule=Host(`${GEONATURE_BACKEND_HOST}`) && PathPrefix(`${GEONATURE_BACKEND_PREFIX?}`)"
      - "traefik.http.routers.geonature-backend.entrypoints=web"
      - "traefik.http.services.geonature-backend.loadbalancer.server.port=8000"

  geonature-frontend:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geonature-frontend.rule=Host(`${GEONATURE_FRONTEND_HOST}`) && PathPrefix(`${GEONATURE_FRONTEND_PREFIX?}`)"
      - "traefik.http.routers.geonature-frontend.entrypoints=web"
      - "traefik.http.services.geonature-frontend.loadbalancer.server.port=80"

  usershub:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usershub.rule=Host(`${USERSHUB_HOST}`) && PathPrefix(`${USERSHUB_PREFIX?}`)"
      - "traefik.http.routers.usershub.entrypoints=web"
      - "traefik.http.services.usershub.loadbalancer.server.port=5001"
