services:

  #------------------------------------Builds section start-----------------------------------#
  base-backend:
    image: ${GEONATURE_BACKEND_IMAGE}-wheels
    build:
      context: sources/GeoNature
      dockerfile: backend/Dockerfile
      target: wheels
    entrypoint: /bin/bash -c exit

  base-frontend-source:
    image: ${GEONATURE_FRONTEND_IMAGE}-source
    build:
      context: sources/GeoNature
      dockerfile: frontend/Dockerfile
      target: source
    entrypoint: /bin/bash -c exit

  base-frontend-nginx:
    image: ${GEONATURE_FRONTEND_IMAGE}-nginx
    build:
      context: sources/GeoNature
      dockerfile: frontend/Dockerfile
      target: prod-base
    entrypoint: /bin/sh -c exit

  userhub-build:
    image: ${USERSHUB_IMAGE}
    build:
      target: prod
      context: sources/UsersHub
    volumes:
      - ./config/usershub:/dist/config/
    entrypoint: /bin/sh -c exit
  #------------------------------------Builds section end------------------------------------#
  geonature-install-db:
    depends_on:
      base-backend:
        condition: service_completed_successfully
    build:
      dockerfile: build/dev/Dockerfile-geonature-backend
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./sources/GeoNature:/sources/GeoNature

  geonature-backend:
    depends_on:
      base-backend:
        condition: service_completed_successfully
    user: "${UID}:${GID}"
    environment:
      TZ:  Europe/Paris
      UID: ${UID}
      GID: ${GID}
    volumes:
      - ./sources/GeoNature:/sources/GeoNature
      - ./sources/gn_module_export:/sources/gn_module_export
      - ./sources/gn_module_dashboard:/sources/gn_module_dashboard
      - ./sources/gn_module_monitoring:/sources/gn_module_monitoring
      - ./sources/protocoles_monitoring:/sources/protocoles_monitoring
      - ./sources/protocoles_monitoring:${GEONATURE_MEDIA_FOLDER:-/dist/media}/monitorings
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro   # si ce fichier n'existe pas sur ton hôte, enlève cette ligne
    build:
      dockerfile: build/dev/Dockerfile-geonature-backend
      args:
        UID: ${UID}
        GID: ${GID}
    labels:
      - "traefik.enable=true"
      - "traefik.owner=${STACK}"
      - "traefik.http.routers.${STACK}-geonature-backend.rule=(Host(`localhost`) || Host(`localhost:${HTTP_PORT}`)) && PathPrefix(`/geonature/api`)"
      - "traefik.http.routers.${STACK}-geonature-backend.entrypoints=web"

  geonature-worker:
    depends_on:
      base-backend:
        condition: service_completed_successfully
    environment:
      TZ:  Europe/Paris
    volumes:
      - ./sources/GeoNature:/sources/GeoNature
      - ./sources/gn_module_export:/sources/gn_module_export
      - ./sources/gn_module_dashboard:/sources/gn_module_dashboard
      - ./sources/gn_module_monitoring:/sources/gn_module_monitoring
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro   # si ce fichier n'existe pas sur ton hôte, enlève cette ligne
    build:
      dockerfile: build/dev/Dockerfile-geonature-backend
    command: watchmedo auto-restart --directory=/sources/GeoNature --pattern=*.py --recursive -- celery -A geonature.celery_app:app worker --beat --schedule-filename=/dist/media/celerybeat-schedule.db

  postgres:
    ports:
      - "${POSTGRES_PORT_ON_HOST:-5432}:${POSTGRES_PORT:-5432}"

  traefik:
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443" 
      - "--providers.docker.constraints=Label(`traefik.owner`, `${STACK}`)"
    ports:
      - "${HTTP_PORT:-8080}:80"
      - "${HTTPS_PORT:-8443}:443"  

  geonature-frontend:
      depends_on:
        base-frontend-source:
          condition: service_completed_successfully
      build:
        context: .
        dockerfile: build/Dockerfile-geonature-frontend
        target: dev-extra
        args:
          GEONATURE_FRONTEND_IMAGE: ${GEONATURE_FRONTEND_IMAGE}
      volumes:
        - ./sources/GeoNature/frontend:/build
        - ./sources/gn_module_dashboard/frontend:/build/external_modules/dashboard
        - ./sources/gn_module_export/frontend:/build/external_modules/export
        - ./sources/gn_module_monitoring/frontend:/build/external_modules/monitorings
        - ./sources/GeoNature/contrib/gn_module_occhab/frontend:/build/external_modules/occhab
        - ./sources/GeoNature/contrib/occtax/frontend:/build/external_modules/occtax
        - ./sources/GeoNature/contrib/gn_module_validation/frontend:/build/external_modules/validation
        - ./build/dev/frontend_entrypoint.sh:/entrypoint.sh
      labels:
        - "traefik.enable=true"
        - "traefik.owner=${STACK}"
        - "traefik.http.routers.${STACK}-geonature.entrypoints=web"
        - "traefik.http.routers.${STACK}-geonature.rule=(Host(`localhost`) || Host(`localhost:${HTTP_PORT}`)) && PathPrefix(`/geonature`)"

  usershub:
      labels:
        - "traefik.enable=true"
        - "traefik.owner=${STACK}"
        - "traefik.http.routers.${STACK}-usershub.entrypoints=web"
        - "traefik.http.routers.${STACK}-usershub.rule=(Host(`localhost`) || Host(`localhost:${HTTP_PORT}`)) && PathPrefix(`/usershub`)"