x-geonature-backend-defaults: &geonature-backend-defaults
  environment:
    GEONATURE_SECRET_KEY_FILE: /run/secrets/geonature_secret_key
    PGPASSFILE: /run/secrets/pgpassfile
  secrets:
    - geonature_secret_key
    - pgpassfile

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: !reset null
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
  geonature-backend:
    <<: *geonature-backend-defaults
  geonature-worker:
    <<: *geonature-backend-defaults
  geonature-install-db:
    <<: *geonature-backend-defaults
  usershub:
    environment:
      PGPASSFILE: /run/secrets/pgpassfile
    secrets:
      - pgpassfile

secrets:
  geonature_secret_key:
    # should contains the secret key content
    file: ./secrets/geonature_secret_key
  postgres_password:
    # should contains the password content
    file: ./secrets/postgres_password
  pgpassfile:
    # should contains "*:*:*:*:geonatpasswd" (see libpq passfile for more infos)
    # /!\ must be chmod 0400 or will be ignored by libpq
    file: ./secrets/pgpassfile
