x-geonature-backend-defaults: &geonature-backend-defaults
  environment:
    GEONATURE_SECRET_KEY_FILE: /run/secrets/geonature_secret_key
  secrets:
    - geonature_secret_key

services:
  geonature-backend:
    <<: *geonature-backend-defaults
  geonature-worker:
    <<: *geonature-backend-defaults
  geonature-install-db:
    <<: *geonature-backend-defaults

secrets:
  geonature_secret_key:
    file: ./secrets/geonature_secret_key
