name: CI - Docker Compose

on:
  push:
    branches:
      - main
      - develop
      - feat/add_ci_dev_compose
  pull_request:
    branches:
      - main
      - develop
jobs:
  test-docker-compose:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
#          - name: "Traefik"
#            env_setup: "cp .env.sample .env"
#            url_frontend: "https://localhost/geonature/"
#            url_backend: "https://localhost/geonature/api/healthz"
#            expected_services: "geonature-backend geonature-frontend postgres redis usershub geonature-worker traefik"
#            env_type: prod
#
#          - name: "Essential"
#            env_setup: "cp .examples_env/.env.sample.without_traefik .env"
#            url_frontend: "http://localhost/#/"
#            url_backend: "localhost:8000/geonature/api/healthz"
#            expected_services: "geonature-backend geonature-frontend postgres redis usershub geonature-worker"
#            env_type: prod
#
#          - name: "Minimal"
#            env_setup: "cp .examples_env/.env.sample.without_db_and_usershub .env"
#            url_frontend: "http://localhost/#/"
#            url_backend: "localhost:8000/geonature/api/gn_commons/config"
#            expected_services: "geonature-backend geonature-frontend geonature-worker redis"
#            env_type: prod

#          - name: "Dev"
#            env_setup: "cp .examples_env/.env.sample.dev .env"
#            url_frontend: "https://localhost/geonature/"
#            url_backend: "https://localhost/geonature/api/healthz"
#            expected_services: "geonature-backend geonature-frontend postgres redis usershub geonature-worker traefik"
#            env_type: dev

          - name: "Dev with Prebuilt DB"
            env_setup: "cp .examples_env/.env.sample.dev_prebuilt_db .env"
            url_frontend: "https://localhost/geonature/"
            url_backend: "https://localhost/geonature/api/healthz"
            expected_services: "geonature-backend geonature-frontend geonature-pre-built-db redis usershub geonature-worker traefik"
            env_type: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y make jq git-lfs curl

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Initialize submodules
        if: matrix.config.env_type == 'dev'
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git submodule update --init --recursive --depth 1


      - name: Built stack
        if: matrix.config.env_type == 'dev'
        run: |
          ${{ matrix.config.env_setup }}
          docker compose up base-backend base-frontend-source base-frontend-nginx userhub-build

      - name: Start stack (${{ matrix.config.name }})
        run: |
          ${{ matrix.config.env_setup }}
          sudo make ${{ matrix.config.env_type }} > /dev/null
          docker ps -a

      - name: Wait for services to be running
        run: sudo .github/scripts/check-services.sh 5 10 "${{ matrix.config.expected_services }}"

      - name: Run integration tests
        run: sudo .github/scripts/integration-tests.sh 5 10 "${{ matrix.config.url_frontend }}" "${{ matrix.config.url_backend }}"

      - name: Tear down
        if: always()
        run: sudo ocker compose down -v
